export const FETCH_PROJECTS_REQUESTS = "FETCH_PROJECTS_REQUESTS";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_REQUESTS";
export const FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_REQUESTS";

export const FETCH_PROJECTS_BY_ID_REQUESTS ="FETCH_PROJECTS_BY_ID_REQUESTS";
export const FETCH_PROJECTS_BY_ID_SUCCESS = "FETCH_PROJECTS_BY_ID_SUCCESS";
export const FETCH_PROJECTS_BY_ID_FAILURE = "FETCH_PROJECTS_BY_ID_FAILURE";

export const CREATE_PROJECTS_REQUESTS ="CREATE_PROJECTS_REQUESTS";
export const CREATE_PROJECTS_SUCCESS = "CREATE_PROJECTS_SUCCESS";
export const CREATE_PROJECTS_FAILURE = "CREATE_PROJECTS_FAILURE";

export const SEARCH_PROJECTS_REQUESTS ="SEARCH_PROJECTS_REQUESTS";
export const SEARCH_PROJECTS_SUCCESS = "SEARCH_PROJECTS_SUCCESS";
export const SEARCH_PROJECTS_FAILURE = "SEARCH_PROJECTS_FAILURE";

export const DELETE_PROJECTS_REQUESTS ="DELETE_PROJECTS_REQUESTS";
export const DELETE_PROJECTS_SUCCESS = "DELETE_PROJECTS_SUCCESS";
export const DELETE_PROJECTS_FAILURE = "DELETE_PROJECTS_FAILURE";

export const INVITE_TO_PROJECTS_REQUESTS ="INVITE_TO_PROJECTS_REQUESTS";
export const INVITE_TO_PROJECTS_SUCCESS = "INVITE_TO_PROJECTS_SUCCESS";
export const INVITE_TO_PROJECTS_FAILURE = "INVITE_TO_PROJECTS_FAILURE";

export const ACCEPT_INVITATION_REQUESTS ="ACCEPT_INVITATION_REQUESTS";
export const ACCEPT_INVITATION_SUCCESS = "ACCEPT_INVITATION_SUCCESS";
export const ACCEPT_INVITATION_FAILURE = "ACCEPT_INVITATION_FAILURE";
